version: "3.7"
services:
  # MySQL
  mysql:
    image: mysql:latest
    volumes:
      - ./common/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=task_timer
      - MYSQL_USER=uperbilite
      - MYSQL_PASSWORD=123456
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  # Redis
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123456
